### ISSUE TITLE
Webiste is down

### ISSUE THREAD

**Issue by silviutroscot** [LechGrzelak/QuantFinanceBook#14]
The website in readme is down; is the URL wrong or is it actually down?

**Comment by LechGrzelak** [comment]
Hello, sorry for that. I had some server issues. I will look into it and hopefully within the next few days, the website will be up again. Best wishes and thanks for letting me know. Lech

**Comment by LechGrzelak** [comment]
it is fixed for a while now.

**Comment by LechGrzelak** [comment]
fixed.
